export const randomPrompts = [
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting by Matisse of a humanoid robot playing chess',
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    'an astronaut playing basketball with cats in space, digital art',
    'a bowl of soup that is also a portal to another dimension, digital art',
    'a stained glass window depicting a hamburger and french fries',
    'synthwave sports car',
    'A man standing in front of a stargate to another dimension',
    'A futuristic cyborg dance club, neon lights',
    'A Space Shuttle flying above Cape Town, digital art',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A comic book cover of a superhero fighting crime',
    'a painting of a fox in the style of Starry Night',
    'mad scientist mixing sparkling chemicals, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'A Samurai riding a Horse on Mars, digital art',
    'Spongebob Squarepants in a horror film',
    'Supervillain, in the style of a Pixar animated movie',
    'Blade Runner Cyberpunk',
    'Baseball player sliding into home base, digital art'
];
